### PR TITLE
Improved Profile and User History

### PR DESCRIPTION
**Pull request by Nivedit24**

### CODE REVIEW

**Comment by Manvi07** [comment]
Maybe we don't need images on these pages. Suggestions, @rishi-s8 @yashikabaan?

**Comment by rishi-s8** [comment]
True. @Manvi07 Moreover, we need to add buttons etc on the right. So, we don't want the columns being congested.

**Comment by Nivedit24** [comment]
It doesn't change much in profile page. And button in admin page can be added in place of approve/reject column. Without photo it looks dull

**Comment by yashikabaan** [comment]
In user.html I don't think there should be a photo.

**Comment by rishi-s8** [comment]
Closing based on the discussion. Can be reopened if there is something else.

**Pull request closed without merging**
