### PR TITLE
Added functionality to Accept/Reschedule/Reject booking request

### PR DESCRIPTION
**Pull request by Nivedit24**
Used Hidden field for ID. Only issue is that after updating request, you have to click the bell icon to see updated list. Also all options change if one is changed. Suggest improvements.

### CODE REVIEW

**Comment by Manvi07** [comment]
**Suggestion**: Remove the drop-down. `Update` button should lead to a form on a separate page with URL `/UpdateStatus/<int:BookingID>`, where the admin can change the status, for that booking, and submit.

**Comment by Manvi07** [comment]
This next page can also be used to display the free slots in a calendar, for the admin to refer to, when rescheduling.

**Comment by Nivedit24** [comment]
How to see the free slots ? Calendar can be included but how to see if slot is used ?

**Comment by Manvi07** [comment]
The calendar would show the booked slots for the selected equipment, using entries from the `Bookings` table. The rest are free.

**Comment by rishi-s8** [comment]
@Nivedit24 can we also add a button to state that a particular entry has been paid?

**Comment by Nivedit24** [comment]
Why do we need a button for that? When Yashika updates the request table with payment status, it can be shown as another column

**Pull request closed without merging**
