### PR TITLE
Br calender

### PR DESCRIPTION
**Pull request by yogeshdeverth155**

### CODE REVIEW

**Comment by Manvi07** [comment]
Is this still in progress?

**Comment by rishi-s8** [comment]
How does this even work?

**Comment by yogeshdeverth155** [comment]
This is just a php function to develop a calendar. We need to link it with an HTML file and  mysql 'booking' table.

**Comment by rishi-s8** [comment]
You'll have to show that it is working with the other pages. We'll merge after it works.

**Comment by rishi-s8** [comment]
Anyways, this is a flask application and using PHP function will need other extensions. See #4

**Comment by rishi-s8** [comment]
Closing in lieu of #25 and #26.

**Pull request closed without merging**
