### PR TITLE
Added new route to Update Bookings

### PR DESCRIPTION
**Pull request by Nivedit24**
Unable to display default value of From and To fields. Else ready to merge.

### CODE REVIEW

**Comment by Manvi07** [comment]
`From` & `To` fields should appear only if **reschedule** is selected. Or can be displayed but not as mandatory.

**Comment by Nivedit24** [comment]
Unable to set default values of From & To. Kindly suggest improvements

**Comment by Manvi07** [comment]
@Nivedit24 
**Suggestion**: We can have a separate page with 4 status buttons, and on clicking **reschedule**, it goes to the page with `From` `To` fields, else for any other choice, reverts to the requests page, after performing the action. This way we won't need default values.

**Comment by rishi-s8** [comment]
@Nivedit24 this looks good. Just one little change, we need something to accept or cancel the rescheduling on the user's side. Maybe 2 buttons? `accept` moves it to confirmed state and `reject` moves it to rejected state?

**Comment by rishi-s8** [comment]
Tested! Works! Merging!

**Pull request merged**
